#!/bin/bash
#ls * | perl -lne 'if ( s/\d+_(-?\d+\.\d++)_(-?\d+\.\d+).*/\1+\2/ ) { print "<a href=\"http://maps.google.com/maps?f=q&hl=en&geocode=&q=$_\">$_</a><br>"; } '
ls * | perl -lne 'if ( s/^(?=\d*_)?(-?\d+\.\d++)_(-?\d+\.\d+).*/\1+\2/ ) { print "<a href=\"http://maps.google.com/maps?f=q&hl=en&geocode=&q=$_\">$_</a><br>"; } '
